[theme]
base="dark"
primaryColor="#1f77b4"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="calibri"




  location ^~ /static {
      proxy_pass http://localhost:8501/static;
  }

  location _stcore/health {
      proxy_pass http://localhost:8501/healthz;
  }

  location ^~ /vendor {
      proxy_pass http://localhost:8501/vendor;
  }

  location /_stcore/stream { 
      proxy_pass http://localhost:8501/stream;
      proxy_http_version 1.1; 
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 86400;
}